image: atnartur/docker:latest

stages:
  - build
  - push
  - deploy

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY


docker-build:
  stage: build
  script:
    - docker-compose up -d --build
  tags:
    - python2k
  only:
    - develop

push:
  stage: push
  script:
    - docker-compose push app nginx
  tags:
    - python2k
  only:
    - develop

run:
  stage: deploy
  script:
    - docker-compose stop
    - docker-compose rm -f
    - docker volume rm kozlov_itis_python2k_project_11900_static
    - docker-compose up -d
  tags:
    - python2k
  only:
    - develop