version: '3'

services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: barbook_django
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - test_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  test_db: