# Generated by Django 3.1.7 on 2021-04-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
        migrations.DeleteModel(
            name="Contest",
        ),
        migrations.AlterModelOptions(
            name="barbookuserjobhistory",
            options={
                "verbose_name": "Место работы",
                "verbose_name_plural": "Места работы",
            },
        ),
        migrations.AlterModelOptions(
            name="cocktailtool",
            options={
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
            },
        ),
    ]
