# Generated by Django 3.1.7 on 2021-04-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0002_auto_20210413_1501"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=1000)),
                ("header", models.CharField(max_length=255)),
                ("img", models.ImageField(upload_to="")),
                ("date", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "db_table": "article",
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="")),
                ("date", models.DateField()),
                ("info", models.TextField(max_length=255)),
                ("name", models.CharField(max_length=40)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Конкурс",
                "verbose_name_plural": "Конкурсы",
                "db_table": "contest",
            },
        ),
        migrations.AlterField(
            model_name="cocktail",
            name="recipe_text",
            field=models.JSONField(),
        ),
    ]
