# Generated by Django 3.1.7 on 2021-04-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0005_auto_20210416_0155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktail",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
