# Generated by Django 3.1.7 on 2021-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0006_auto_20210416_0155"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="author_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
