# Generated by Django 3.1.7 on 2021-04-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0007_message_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="still_relevant",
            field=models.BooleanField(default=True),
        ),
    ]
