# Generated by Django 3.1.7 on 2021-04-30 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0008_auto_20210424_2146"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cocktailrecipe",
            name="cocktail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe",
                to="barbook_app.cocktail",
            ),
        ),
        migrations.CreateModel(
            name="PasswordDrop",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jwt_token", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "drop_password",
            },
        ),
    ]
