# Generated by Django 3.1.7 on 2021-04-30 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barbook_app", "0009_auto_20210430_0447"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passworddrop",
            name="jwt_token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
