# Generated by Django 3.1.7 on 2022-06-22 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbook_app', '0010_auto_20210430_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartool',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='bartool',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='small_img'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='small_img'),
        ),
        migrations.AlterField(
            model_name='cocktailtool',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cocktail_tool', to='barbook_app.cocktail'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='small_img',
            field=models.ImageField(blank=True, null=True, upload_to='small_img'),
        ),
    ]
