name: TelegramNotification

on:
  push:
    branches:
      - 'main'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: PushNotify
        uses: appleboy/telegram-action@master
        with:
          token: ${{BarBookEnv.TELEGRAM_BOT_TOKEN}}
          to: ${{ BarBookEnv.CHAT_ID }}
          message: |
            ${{ github.actor }} just pushed ${{ github.ref }} into ${{ github.repository }} with comment "${{ github.event.head_commit.message }}"
            ${{ github.event.compare }}