name: TelegramNotification

on:
  push:
    branches:
      - 'main'
  workflow_run:
    workflows: [ "Run unittests" ]
    branches: [ main ]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: PushNotify
        uses: appleboy/telegram-action@master
        with:
          token: ${{secrets.TELEGRAM_BOT_TOKEN}}
          to: ${{ secrets.CHAT_ID }}
          message: |
            ${{ github.actor }} just pushed ${{ github.ref }} into ${{ github.repository }} with comment "${{ github.event.head_commit.message }}"
            ${{ github.event.compare }}